///Generic Dimensions
const MARGIN_SMALL = 4.0;
const MARGIN_MEDIUM = 8.0;
const MARGIN_MEDIUM_2 = 15.0;
const MARGIN_MEDIUM_LARGE = 16.0;
const MARGIN_MEDIUM_XLARGE = 30.0;

const TEXT_HEADING_1X = 24.0;
const TEXT_REGULAR = 8.0;
const TEXT_REGULAR_1X = 10.0;
const TEXT_REGULAR_2X = 12.0;
const TEXT_REGULAR_3X = 14.0;
const TEXT_REGULAR_4X = 18.0;
const TEXT_REGULAR_5X = 20.0;
const SHOWTIMES_TEXT = 24.0;
const MOVIE_DETAILS_RATING_TEXT = 46.0;
const MOVIE_DETAILS_PLAY_BUTTON_HEIGHT = 40.0;
const MOVIE_DETAILS_PLAY_BUTTON_HEIGHT_2 = 80.0;

///App Specific
const BANNER_SECTION_HEIGHT = 200.0;
const BANNER_PLAY_BUTTON_SIZE = 52.0;
const MOVIE_LIST_HEIGHT = 350.0;
const MOVIE_LIST_ITEM_WIDTH = 150.0;
const ACTOR_LIST_HEIGHT = 200.0;
const SHOW_CASES_VIEW_WIDTH = 300.0;
const FAVORITE_ICON_SIZE = 30.0;
const MOVIE_SHOWTIMES_HEIGHT = 180.0;
const SLIVER_APP_BAR_EXPANDED_HEIGHT = 300.0;
const SLIVER_APP_BAR_COLLAPSED_HEIGHT = 120.0;
