
const MAIN_SCREEN_APP_BAR_TITLE="Discover";
const HOME_SCREEN_MOVIE_TITLE_TEXT="BEST POPULAR FILMS AND SERIALS";
const HOME_SCREEN_MOVIE_SHOWTIMES="Check Movie\nShowtimes";
const HOME_SCREEN_MOVIE_SHOWTIMES_SEE_MORE="SEE MORE";
const SHOW_CASE_TITLE_TEXT="SHOWCASES";
const MORE_SHOW_CASE_TITLE_TEXT="MORE SHOWCASES";
const BEST_ACTORS_TEXT="BEST ACTORS";
const MORE_ACTORS_TEXT="MORE ACTORS";
const MOVIE_DETAILS_ACTORS="ACTORS";
const MOVIE_DETAILS_CREATORS="CREATORS";
const MOVIE_DETAILS_MORE_CREATORS="MORE CREATORS";
const MOVIE_DETAILS_STORYLINE="STORYLINE";
const MOVIE_DETAILS_PLAY_TRAILER="PLAY TRAILER";
const MOVIE_DETAILS_RATE_MOVIE="RATE MOVIE";
